highlighter:  true
permalink: /blog/:year/:month/:day/:title.html
exclude:   [ README.md, Gemfile ]
sass:
  sass_dir: css
navigation:
 - title: Home
   url: /
 - title: Documentation
   url: /documentation.html
 - title: Download
   url: /download.html
 - title: Contribute
   url: https://github.com/jarves/jarves/issues
